[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.x"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max_old_space_size=8192"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "@tensorflow/tfjs-node"]

[dev]
  framework = "next"
  target = "experimental"
  command = "npm run dev"
  publish = ".next"
  port = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "npm run build"
  environment = { NODE_ENV = "production" }
